### ISSUE TITLE
Edit by JOSM-remote does not work

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#32] opened 2013-11-21 09:06 UTC
im Menü "Bearbeiten"
funktioniert "JOSM remote" nicht.
Fehlermeldung: "Bereich zu gross"
(auch wenn der Bereich z=18 ist)

gleicher Fehler in:
http://map.openseamap.org/
http://seamark.bplaced.net/lights/

**Comment by aAXEe** [comment] 2015-10-17 12:32
The "send to JOSM" function works normaly.
The problem Nautic describes happens than JOSM tries to download very much data in one request. The osm main server rejects this to avoid overload. This is normal behaviour from JOSM. It also happens when you use the JOSM internal dialog for data downloading. 
The size of the region is not limited by the size but by the number of datapoints. So is it not possible do determine if the download will fail before trying to do so. That is why we can not check this on the map.
From my point of view this issue can be closed. It is not a bug in our online chart (if it is a bug at all).

**Comment by ehrenfeu** [comment] 2015-10-20 21:15
@aAXEe sounds reasonable, I'm closing the issue.
@Skippern do you have any references to the JOSM tickets you mentioned in your comment from August last year?

**Closed by ehrenfeu** 2015-10-20 21:15 UTC
Labels: bug
