### ISSUE TITLE
Permalink Wikipedia-Gallery (Thumbnails) not working

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#51] opened 2014-09-28 07:33 UTC
Permalinks with Wikipedia-Thumbnails do not work.

Marker and Thumbnails result in the same permalink layer-string:
* [0FTFFFTFFTTBFFFFFTFF](http://map.openseamap.org/index.php?lang=de&zoom=15&lat=54.18173&lon=7.89859&layers=0FTFFFTFFTTBFFFFFTFF) (Marker)
* [0FTFFFTFFTTBFFFFFTFF](http://map.openseamap.org/index.php?lang=de&zoom=15&lat=54.18173&lon=7.89859&layers=0FTFFFTFFTTBFFFFFTFF) (Thumbnails)

Wrong: code does not differ between Marker and Thumbnails

**Comment by ehrenfeu** [comment] 2015-01-16 12:16
Steps to reproduce:

1. Enable `View > Wikipedia-Links > Marker`
1. Click the "Permalink" at the right bottom
1. Enable `View > Wikipedia-Links > Thumbnails`
1. Click the "Permalink" at the right bottom again

Results in the same address being generated.

**Comment by ehrenfeu** [comment] 2015-01-16 12:31
This is a duplicate of #24.

**Closed by ehrenfeu** 2015-01-16 12:31 UTC
Labels: bug, duplicate
