### ISSUE TITLE
Cursor in Popup

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#38] opened 2013-12-05 15:05 UTC
When clicking into a popup (harbour, gauge), a cursor shows up.

This is wrong because there is no edit possible.

**Comment by ehrenfeu** [comment] 2015-01-15 14:17
I'm pretty sure this is a duplicate of #35.

**Comment by ehrenfeu** [comment] 2015-01-20 08:54
Closing as a duplicate.

**Closed by ehrenfeu** 2015-01-20 08:54 UTC
Labels: bug, duplicate
